### ISSUE TITLE
更新到最新版本后执行#更新面板提示“请求失败” TypeError: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by sahajata** [yoimiya-kokomi/miao-plugin#135]
更新到最新版本后执行#更新面板提示：
TypeError: Cannot read properties of undefined (reading 'url')
    at ProfileServ.getCfg (file:///C:/Yunzai-Bot/plugins/miao-plugin/models/ProfileServ.js:24:40)
    at ProfileServ.getReqParam (file:///C:/Yunzai-Bot/plugins/miao-plugin/models/ProfileServ.js:35:20)
    at ProfileReq.request (file:///C:/Yunzai-Bot/plugins/miao-plugin/models/ProfileReq.js:55:31)
    at Object.request (file:///C:/Yunzai-Bot/plugins/miao-plugin/components/Profile.js:23:24)
    at Module.getProfile (file:///C:/Yunzai-Bot/plugins/miao-plugin/apps/character/profile-common.js:189:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async miao.dispatch (file:///C:/Yunzai-Bot/plugins/miao-plugin/adapter/index.js:44:19)
    at async PluginsLoader.deal (file:///C:/Yunzai-Bot/lib/plugins/loader.js:250:52)
[YzBot][08:41:44.608][MARK] [miao-plugin][dispatch] #更新面板 处理完成 7ms

Yunzai-Bot使用的是3.0版本，并且确认云服务器可访问[enka](https://enka.shinshin.moe/)

**Comment by w1915591935** [comment]
我也是这样

**Comment by yoimiya-kokomi** [comment]
删除config/profile.js，重启
如需自定义配置请复制config/profile_default.js，不要复制system下的

**Comment by yoimiya-kokomi** [comment]
稍晚修复
短期内修复方案为复制miao-plugin目录里面 config/profile_default.js 为 config/profile.js，重启

**Comment by yoimiya-kokomi** [comment]
已经修复，更新至最新版即可
