### ISSUE TITLE
使用命令 #北斗图鉴 时会产生异常

### ISSUE THREAD

**Issue by samzh** [yoimiya-kokomi/miao-plugin#163]
具体异常如下：

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.getAttrList (file:///server/Yunzai-Bot/plugins/miao-plugin/models/character-lib/CharMeta.js:72:25)
    at Character.getAttrList (file:///server/Yunzai-Bot/plugins/miao-plugin/models/Character.js:92:21)
    at renderWiki (file:///server/Yunzai-Bot/plugins/miao-plugin/apps/wiki.js:116:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.wiki (file:///server/Yunzai-Bot/plugins/miao-plugin/apps/wiki.js:68:12)
    at async miao.dispatch (file:///server/Yunzai-Bot/plugins/miao-plugin/adapter/v3-entrance.js:41:19)
    at async PluginsLoader.deal (file:///server/Yunzai-Bot/lib/plugins/loader.js:250:52)
```

**Comment by samzh** [comment]
更新今天的版本后正常了故关闭

**Comment by yoimiya-kokomi** [comment]
嗯，北斗的角色数据里有个字段抓取失败了，已经重新抓取
