### ISSUE TITLE
更新面板请求失败

### ISSUE THREAD

**Issue by SunflowerYuuka** [yoimiya-kokomi/miao-plugin#177]
更新面板请求失败，但是我去enka网站尝试手动查询是可以的，请问是什么问题呢？

**Comment by SunflowerYuuka** [comment]
![Z)4_SPCXU~ZIXFO UI1VE@M](https://user-images.githubusercontent.com/78639553/189919065-104f7e91-296d-4c15-85d7-320ffeef4ac1.png)

**Comment by TerryW-tx** [comment]
同样碰到了这个问题，log里显示处理完成并且没报错，但是回复是服务负载较高

**Comment by ziiqq** [comment]
同问

**Comment by VeritasAlex** [comment]
同样的问题

**Comment by lanlanwa** [comment]
同

**Comment by Hanserwei** [comment]
[2022-09-14T11:28:55.724] [MARK] [原神分享群(leon)] #更新面板:character
[2022-09-14T11:28:55.725] [MARK] [原神分享群(leon)] #更新面板:getProfile
[2022-09-14T11:28:56.025] [INFO] succeed to send: [Group(603998908)] 开始获取数据，可能会需要一定时间~
面板请求错误 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///C:/Users/Administrator/Desktop/%E4%BA%91%E5%B4%BD/Yunzai-Bot/node_modules/_node-fetch@3.2.10@node-fetch/src/body.js:149:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Proxy.request (file:///C:/Users/Administrator/Desktop/%E4%BA%91%E5%B4%BD/Yunzai-Bot/plugins/miao-plugin/models/ProfileReq.js:71:14)
    at async Object.request (file:///C:/Users/Administrator/Desktop/%E4%BA%91%E5%B4%BD/Yunzai-Bot/plugins/miao-plugin/components/Profile.js:23:14)
    at async Module.getProfile (file:///C:/Users/Administrator/Desktop/%E4%BA%91%E5%B4%BD/Yunzai-Bot/plugins/miao-plugin/apps/character/profile-common.js:189:14)
    at async Object.dealMsg (file:///C:/Users/Administrator/Desktop/%E4%BA%91%E5%B4%BD/Yunzai-Bot/lib/dealMsg.js:234:19)
[2022-09-14T11:28:56.557] [INFO] succeed to send: [Group(603998908)] 请求失败，可能是服务负载较高，请稍后重试...

**Comment by q35654046** [comment]
同样的问题......

**Comment by ziiqq** [comment]
喵佬修了，把喵喵更新一下就行了

**Comment by yoimiya-kokomi** [comment]
更新至最新版miao-plugin，应该不会再出现上述报错了

**Comment by canyi2** [comment]
已更新至喵喵最新版（指令更新）依旧不能用，报同样的日志

**Comment by canyi2** [comment]
指令更新之后依旧不能使用，继续报错，需再plugin手动删除喵喵，重新安装最新版插件，可解决
