### ISSUE TITLE
上传角色图像报错

### ISSUE THREAD

**Issue by Hanyue233** [yoimiya-kokomi/miao-plugin#188]
[YzBot][16:51:40.934][ERRO] [miao-plugin][dispatch]
[YzBot][16:51:40.935][ERRO] TypeError: Cannot read properties of undefined (reading 'time')
    at Module.uploadCharacterImg (file:///D:/Yunzai-Bot/Yunzai-BotV3/plugins/miao-plugin/apps/character/character-img-upload.js:49:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async miao.dispatch (file:///D:/Yunzai-Bot/Yunzai-BotV3/plugins/miao-plugin/adapter/v3-entrance.js:41:19)
    at async PluginsLoader.deal (file:///D:/Yunzai-Bot/Yunzai-BotV3/lib/plugins/loader.js:250:52)

**Comment by liuzj288** [comment]
同bug
![image](https://user-images.githubusercontent.com/13833404/191131425-816c21c5-4ea4-43c9-93a3-e0959b31c2d5.png)

**Comment by GoverSky** [comment]
我也发现这个bug，只有at人才能添加上，我自己改了下凑合用..等大佬修
![image](https://user-images.githubusercontent.com/16715284/191882952-f2de8302-20f7-46cb-8b58-edb96d656118.png)
