### ISSUE TITLE
在设置好公共CK的情况下，极个别成员查看角色信息会报错

### ISSUE THREAD

**Issue by davidelectricfree** [yoimiya-kokomi/miao-plugin#22]
重做了服务器系统以后，设置公共CK，在所有人都没有绑定私人CK的情况下，绝大部分人能正常使用角色卡牌功能，极少数群员无法使用查询信息功能：如老婆，角色卡牌等，报错信息如下所示。

[2022-05-22T22:50:35.831] [MARK] command - [xxx] #角色卡片:character
[2022-05-22T22:50:35.834] [MARK] command - [xxx] #角色卡片:roleCard
[2022-05-22T22:50:35.836] [ERROR] error - mysInfo.roleCard
[2022-05-22T22:50:35.837] [ERROR] error - TypeError: cookieUser.getCookie is not a function
    at Object.Msg.getMysApi (file:///C:/GenshinBot/Yunzai-Bot/lib/components/Msg.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GroupMessage.e.getMysApi (file:///C:/GenshinBot/Yunzai-Bot/lib/dealMsg.js:144:12)
    at async getMysApi (file:///C:/GenshinBot/Yunzai-Bot/lib/app/mysInfo.js:122:10)
    at async Module.roleCard (file:///C:/GenshinBot/Yunzai-Bot/lib/app/mysInfo.js:515:16)
    at async Object.dealMsg (file:///C:/GenshinBot/Yunzai-Bot/lib/dealMsg.js:191:19)

**Comment by davidelectricfree** [comment]
更新，发现每次出现极少部分成员无法查询的情况，使用#充值用户统计 功能即可恢复，恢复以后，过几天，又会出现上面的情况，然后使用前面的指令又可恢复，不知道程序是不是有BUG

**Comment by NomadThanatos** [comment]
Duplicate as https://github.com/Le-niao/Yunzai-Bot/issues/148

**Comment by yoimiya-kokomi** [comment]
mark一下
底层的cookie分配与处理问题，后面会升级下yunzai相关逻辑

**Comment by ImHeroZero** [comment]
> mark一下 底层的cookie分配与处理问题，后面会升级下yunzai相关逻辑

大佬我在config.js看见了一个cookie一天只能查30次的说明,是这个原因吗?

**Comment by yoimiya-kokomi** [comment]
此问题已在2.1.9修复，可尝试切换至此分支进行更新
https://github.com/yoimiya-kokomi/Yunzai-Bot

**Comment by davidelectricfree** [comment]
> 此问题已在2.1.9修复，可尝试切换至此分支进行更新
> https://github.com/yoimiya-kokomi/Yunzai-Bot

已经fork，并把原项目的git更新地址更改为你发的链接。
