### ISSUE TITLE
查询部分角色面板报错

### ISSUE THREAD

**Issue by ChengysTHU** [yoimiya-kokomi/miao-plugin#238]
出现错误的commit： 6e3728d3b8342beb934adafe5111e14f2dc51336
群友查询温迪面板时触发，其他角色未测试。
同时测试其他角色，如“心海面板”， ”宵宫面板“，表现正常
log如下：
```
[YzBot][22:28:10.603][ERRO] [喵喵:角色面板][profileDetail]
[YzBot][22:28:10.605][ERRO] TypeError: Cannot read properties of undefined (reading 'type')
    at Object.getMultiple (file:///root/Yunzai-Bot/plugins/miao-plugin/models/profile-lib/DmgMastery.js:6:17)
    at Object.calcRet (file:///root/Yunzai-Bot/plugins/miao-plugin/models/profile-lib/DmgCalc.js:88:74)
    at dmgFn (file:///root/Yunzai-Bot/plugins/miao-plugin/models/profile-lib/DmgCalc.js:153:22)
    at Object.dmg (file:///root/Yunzai-Bot/plugins/miao-plugin/resources/meta/character/%E6%B8%A9%E8%BF%AA/calc.js:14:14)
    at file:///root/Yunzai-Bot/plugins/miao-plugin/models/ProfileDmg.js:138:30
    at arrayEach (/root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/root/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:9410:14)
    at Proxy.calcData (file:///root/Yunzai-Bot/plugins/miao-plugin/models/ProfileDmg.js:118:12)
    at async Proxy.calcDmg (file:///root/Yunzai-Bot/plugins/miao-plugin/models/ProfileData.js:157:12)
    at async renderProfile (file:///root/Yunzai-Bot/plugins/miao-plugin/apps/character/ProfileDetail.js:63:17)
```

倒回上一commit （e24726b391d99534eca761a0b5455d72e0c3770b）重复测试，问题未复现

**Comment by yoimiya-kokomi** [comment]
更新，已经fix了
