### ISSUE TITLE
面板请求错误 SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by BZBY** [yoimiya-kokomi/miao-plugin#286]
面板请求错误 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Proxy.request (file:///C:/paimeng/LittlePaimon/Yunzai-Bot/plugins/miao-plugin/models/ProfileReq.js:80:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.request (file:///C:/paimeng/LittlePaimon/Yunzai-Bot/plugins/miao-plugin/components/Profile.js:23:14)
    at async cls.getProfile (file:///C:/paimeng/LittlePaimon/Yunzai-Bot/plugins/miao-plugin/apps/character/ProfileCommon.js:184:14)
    at async cls.<computed> [as profileRefresh] (file:///C:/paimeng/LittlePaimon/Yunzai-Bot/plugins/miao-plugin/components/App.js:87:16)
    at async PluginsLoader.deal (file:///C:/paimeng/LittlePaimon/Yunzai-Bot/lib/plugins/loader.js:251:52)

**Comment by unknown10777** [comment]
cloudflare问题，更换国内节点即可解决。
