### ISSUE TITLE
#更新面板 提示文件找不到 路径问题报错 docker环境运行

### ISSUE THREAD

**Issue by louyongjiu** [yoimiya-kokomi/miao-plugin#470]
#更新面板 提示文件找不到 路径问题 no such file or directory, open '/app/Yunzai-Bot///data/UserData/128693147.json'

[YzBot][21:48:26.522][MARK] [喵喵:角色面板][profileRefresh][私聊][　(921944921)] #更新面板
[YzBot][21:48:26.527][ERRO] [喵喵:角色面板][profileRefresh]
[YzBot][21:48:26.528][ERRO] Error: ENOENT: no such file or directory, open '/app/Yunzai-Bot///data/UserData/128693147.json'
    at Object.openSync (node:fs:600:3)
    at Object.writeFileSync (node:fs:2221:35)
    at Object.writeJSON (file:///app/Yunzai-Bot/plugins/miao-plugin/components/Data.js:59:15)
    at Proxy.save (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:107:10)
    at Proxy.reload (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:82:12)
    at new Player (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:29:10)
    at Player.create (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:47:20)
    at cls.refresh (file:///app/Yunzai-Bot/plugins/miao-plugin/apps/profile/ProfileList.js:19:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async cls.<computed> [as profileRefresh] (file:///app/Yunzai-Bot/plugins/miao-plugin/components/App.js:93:16)

**Comment by ymxccccc** [comment]
Error: ENOENT: no such file or directory, open '/root/TRSS_Yunzai/Yunzai///data/UserData/197125319.json'
at Object.openSync (node:fs:585:3)
at Object.writeFileSync (node:fs:2229:35)
at Object.writeJSON (file:///root/TRSS_Yunzai/Yunzai/plugins/miao-plugin/components/Data.js:59:15)
at Proxy.save (file:///root/TRSS_Yunzai/Yunzai/plugins/miao-plugin/models/Player.js:107:10)
at Proxy.reload (file:///root/TRSS_Yunzai/Yunzai/plugins/miao-plugin/models/Player.js:82:12)
at new Player (file:///root/TRSS_Yunzai/Yunzai/plugins/miao-plugin/models/Player.js:29:10)
at Player.create (file:///root/TRSS_Yunzai/Yunzai/plugins/miao-plugin/models/Player.js:47:20)
at cls.render (file:///root/TRSS_Yunzai/Yunzai/plugins/miao-plugin/apps/profile/ProfileList.js:75:25)
at async cls. [as profileList] (file:///root/TRSS_Yunzai/Yunzai/plugins/miao-plugin/components/App.js:93:16)
at async PluginsLoader.deal (file:///root/TRSS_Yunzai/Yunzai/lib/plugins/loader.js:251:52)
我的也是相同情况，不仅面板，而且深渊也是这样报错

**Comment by ZOG-N** [comment]
> #更新面板 提示文件找不到 路径问题 no such file or directory, open '/app/Yunzai-Bot///data/UserData/128693147.json'
> 
> [YzBot][21:48:26.522][MARK] [喵喵:角色面板][profileRefresh][私聊][　(921944921)] #更新面板 [YzBot][21:48:26.527][ERRO] [喵喵:角色面板][profileRefresh] [YzBot][21:48:26.528][ERRO] Error: ENOENT: no such file or directory, open '/app/Yunzai-Bot///data/UserData/128693147.json' at Object.openSync (node:fs:600:3) at Object.writeFileSync (node:fs:2221:35) at Object.writeJSON (file:///app/Yunzai-Bot/plugins/miao-plugin/components/Data.js:59:15) at Proxy.save (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:107:10) at Proxy.reload (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:82:12) at new Player (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:29:10) at Player.create (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:47:20) at cls.refresh (file:///app/Yunzai-Bot/plugins/miao-plugin/apps/profile/ProfileList.js:19:25) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async cls. [as profileRefresh] (file:///app/Yunzai-Bot/plugins/miao-plugin/components/App.js:93:16)

进入容器内 /app/Yunzai-Bot/data/UserData，容器内的<UserData>名称错了，容器内的是<userData>，改成<UserData>，U 大写

**Comment by yoimiya-kokomi** [comment]
更新至最新版miao-plugin试下
预建立的一个目录大小写有误

**Comment by louyongjiu** [comment]
> > #更新面板 提示文件找不到 路径问题 no such file or directory, open '/app/Yunzai-Bot///data/UserData/128693147.json'
> > [YzBot][21:48:26.522][MARK] [喵喵:角色面板][profileRefresh][私聊][　(921944921)] #更新面板 [YzBot][21:48:26.527][ERRO] [喵喵:角色面板][profileRefresh] [YzBot][21:48:26.528][ERRO] Error: ENOENT: no such file or directory, open '/app/Yunzai-Bot///data/UserData/128693147.json' at Object.openSync (node:fs:600:3) at Object.writeFileSync (node:fs:2221:35) at Object.writeJSON (file:///app/Yunzai-Bot/plugins/miao-plugin/components/Data.js:59:15) at Proxy.save (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:107:10) at Proxy.reload (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:82:12) at new Player (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:29:10) at Player.create (file:///app/Yunzai-Bot/plugins/miao-plugin/models/Player.js:47:20) at cls.refresh (file:///app/Yunzai-Bot/plugins/miao-plugin/apps/profile/ProfileList.js:19:25) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async cls. [as profileRefresh] (file:///app/Yunzai-Bot/plugins/miao-plugin/components/App.js:93:16)
> 
> 进入容器内 /app/Yunzai-Bot/data/UserData，容器内的（UserData）名称错了，容器内的是（userData），改成（UserData），U 大写

修改了文件目录名，把userData 改为 UserData，可以正常使用了
