### ISSUE TITLE
上传角色面板图失败

### ISSUE THREAD

**Issue by meng-fucius** [yoimiya-kokomi/miao-plugin#510]
[YzBot][17:47:44.911][INFO] recv from: [Group: 原神<$ÿĀ>(199584776), Member: 宫常草明(494089941)] #上传绫华面板图
{image:B1E5E8B109A29F773969E994D5A70CE6}
[YzBot][17:47:44.914][MARK] [喵喵:角色面板][uploadImg][原神<$ÿĀ>(宫常草明)] #上传绫华面板图
[YzBot][17:47:44.915][ERRO] [喵喵:角色面板][uploadImg]
[YzBot][17:47:44.915][ERRO] Error: ENOENT: no such file or directory, mkdir '/app/Yunzai-Bot/plugins//app/Yunzai-Bot/plugins/miao-plugin/resources//profile/'
    at Object.mkdirSync (node:fs:1395:3)
    at file:///app/Yunzai-Bot/plugins/miao-plugin/components/Data.js:33:16
    at Array.forEach (<anonymous>)
    at Object.createDir (file:///app/Yunzai-Bot/plugins/miao-plugin/components/Data.js:27:14)
    at saveImages (file:///app/Yunzai-Bot/plugins/miao-plugin/apps/character/ImgUpload.js:92:10)
    at cls.uploadCharacterImg (file:///app/Yunzai-Bot/plugins/miao-plugin/apps/character/ImgUpload.js:81:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async cls.<computed> [as uploadImg] (file:///app/Yunzai-Bot/plugins/miao-plugin/components/App.js:93:16)
    at async PluginsLoader.deal (file:///app/Yunzai-Bot/lib/plugins/loader.js:251:52)

使用#上传绫花面板图 命令失败 上面是日志，/app/Yunzai-Bot/plugins/这个路径前缀重复了

**Comment by meng-fucius** [comment]
最新版本已修复
