### ISSUE TITLE
星铁更新面板在角色未携带光锥时报错

### ISSUE THREAD

**Issue by Haocen2004** [yoimiya-kokomi/miao-plugin#579]
报错日志：
```
[MiaoYz][11:07:04.273][ERRO] [喵喵:角色面板][profileRefresh]
[MiaoYz][11:07:04.275][ERRO] TypeError: weapon.calcAttr is not a function
    at AttrCalc.setWeaponAttr (file:///root/Yunzai-Bot-main/Miao-Yunzai/plugins/miao-plugin/models/profile/AttrCalc.js:162:27)
    at AttrCalc.calc (file:///root/Yunzai-Bot-main/Miao-Yunzai/plugins/miao-plugin/models/profile/AttrCalc.js:66:10)
    at Proxy.calcAttr (file:///root/Yunzai-Bot-main/Miao-Yunzai/plugins/miao-plugin/models/ProfileData.js:80:28)
    at new ProfileData (file:///root/Yunzai-Bot-main/Miao-Yunzai/plugins/miao-plugin/models/ProfileData.js:12:12)
    at ProfileData.create (file:///root/Yunzai-Bot-main/Miao-Yunzai/plugins/miao-plugin/models/ProfileData.js:57:19)
    at Proxy.getProfile (file:///root/Yunzai-Bot-main/Miao-Yunzai/plugins/miao-plugin/models/AvatarData.js:205:24)
    at file:///root/Yunzai-Bot-main/Miao-Yunzai/plugins/miao-plugin/models/Player.js:235:28
    at /root/Yunzai-Bot-main/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/root/Yunzai-Bot-main/Miao-Yunzai/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:3032:24)
```
请求api部分返回结果
```
${url}profile/data?uid=100493858&qq=${qq}&token=${token}&version=2&game=sr
{"id":1108,"costume":0,"cons":0,"level":20,"promote":1,"talent":{"1108001":1,"1108002":1,"1108003":1,"1108004":1,"1108007":1},"weapon":{"id":0,"level":0,"promote":0,"affix":0},"artis":{}}
```
可请求uid：100493858 验证 挂了一个光锥遗器都没有的角色专门用于debug

**Comment by Katou-Kouseki** [comment]
确实有这个问题

**Comment by yoimiya-kokomi** [comment]
嗯，下个版本fix
