### ISSUE TITLE
用了sudo和chmod 还是有问题Error: EACCES: permission denied, open 'logs/command.2023-06-23.log

### ISSUE THREAD

**Issue by YvetteVv** [yoimiya-kokomi/miao-plugin#602]
``node:fs:594
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, open 'logs/command.2023-06-23.log'
    at Object.openSync (node:fs:594:3)
    at Object.writeFileSync (node:fs:2207:35)
    at Object.appendFileSync (node:fs:2269:6)
    at DateRollingFileStream._renewWriteStream (/home/lighthouse/Yunzai-Bot/node_modules/.pnpm/streamroller@3.1.5/node_modules/streamroller/lib/RollingFileWriteStream.js:312:8)
    at new RollingFileWriteStream (/home/lighthouse/Yunzai-Bot/node_modules/.pnpm/streamroller@3.1.5/node_modules/streamroller/lib/RollingFileWriteStream.js:94:10)
    at new DateRollingFileStream (/home/lighthouse/Yunzai-Bot/node_modules/.pnpm/streamroller@3.1.5/node_modules/streamroller/lib/DateRollingFileStream.js:31:5)
    at openTheStream (/home/lighthouse/Yunzai-Bot/node_modules/.pnpm/log4js@6.9.1/node_modules/log4js/lib/appenders/dateFile.js:7:18)
    at appender (/home/lighthouse/Yunzai-Bot/node_modules/.pnpm/log4js@6.9.1/node_modules/log4js/lib/appenders/dateFile.js:36:18)
    at Object.configure (/home/lighthouse/Yunzai-Bot/node_modules/.pnpm/log4js@6.9.1/node_modules/log4js/lib/appenders/dateFile.js:67:10)
    at /home/lighthouse/Yunzai-Bot/node_modules/.pnpm/log4js@6.9.1/node_modules/log4js/lib/appenders/index.js:117:29 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'logs/command.2023-06-23.log'
}

**Comment by JadeVane** [comment]
用chown改一下所属用户试试，最好把整个yunzai-bot目录都设为当前运行命令的用户：
`chown 用户组:用户名 /home/lighthouse/Yunzai-Bot/ -R`
