### ISSUE TITLE
喵喵帮助图片生成失败puppeteer Chromium 强制关闭重启

### ISSUE THREAD

**Issue by AUndead** [yoimiya-kokomi/miao-plugin#733]
[TRSSYz][18:34:14.204][INFO] [3889000998] recv from Guild(7901030043031741737)Channel(634047285): 帮助
[TRSSYz][18:34:14.204][INFO] [3889000998] 频道消息：[qg_7901030043031741737-634047285, 泠顼(qg_18207061512513127513)] 帮助
[TRSSYz][18:34:14.229][INFO] [喵喵:喵喵帮助][help][qg_7901030043031741737-634047285, 泠顼(qg_18207061512513127513)] 帮助
[TRSSYz][18:34:14.234][INFO] puppeteer Chromium 启动中...
[TRSSYz][18:34:14.546][INFO] puppeteer Chromium 启动成功 ws://127.0.0.1:40633/devtools/browser/9a1a3e6b-8d16-44d9-9724-912e5b4abf82
[TRSSYz][18:34:14.587][ERRO] [图片生成][miao-plugin/help/index] 图片生成失败 Error: net::ERR_FILE_NOT_FOUND at file:///genshin/qbot/Yunzai/temp/html/miao-plugin/help/index/index.html
    at navigate (file:///genshin/qbot/Yunzai/node_modules/.pnpm/puppeteer-core@22.6.3/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:168:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Deferred.race (file:///genshin/qbot/Yunzai/node_modules/.pnpm/puppeteer-core@22.6.3/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:33:20)
    at async CdpFrame.goto (file:///genshin/qbot/Yunzai/node_modules/.pnpm/puppeteer-core@22.6.3/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:134:25)
    at async CdpPage.goto (file:///genshin/qbot/Yunzai/node_modules/.pnpm/puppeteer-core@22.6.3/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:563:20)
    at async Puppeteer.screenshot [as render] (file:///genshin/qbot/Yunzai/renderers/puppeteer/lib/puppeteer.js:187:7)
    at async renderer.screenshot (file:///genshin/qbot/Yunzai/lib/puppeteer/puppeteer.js:10:15)
    at async Runtime.render (file:///genshin/qbot/Yunzai/lib/plugins/runtime.js:229:18)
    at async cls.render (file:///genshin/qbot/Yunzai/plugins/miao-plugin/apps/help/Help.js:61:12)
    at async cls.<computed> [as help] (file:///genshin/qbot/Yunzai/plugins/miao-plugin/components/App.js:96:18)
[TRSSYz][18:34:14.588][INFO] puppeteer Chromium 强制关闭重启...
[TRSSYz][18:34:14.588][INFO] puppeteer Chromium 启动中...
[TRSSYz][18:34:14.589][MARK] [喵喵:喵喵帮助][help] 帮助 处理完成 360ms
[TRSSYz][18:34:14.902][INFO] puppeteer Chromium 启动成功 ws://127.0.0.1:37373/devtools/browser/5e113bfc-ffb1-4dfd-8b72-77324fbfe52e

**Comment by misaki-me** [comment]
我也遇到这个问题了，请问你的解决了吗

**Comment by AUndead** [comment]
> 我也遇到这个问题了，请问你的解决了吗

网络问题 换个运营商就行了
