### ISSUE TITLE
喵喵插件加载错误

### ISSUE THREAD

**Issue by Yamakoer** [yoimiya-kokomi/miao-plugin#74]
![QQ图片20220724185807](https://user-images.githubusercontent.com/53447185/180669221-d02c78bb-b39d-4b37-8383-5d1a2bb34b0b.png)

**Comment by 4682265664** [comment]
显示 无法读取空的属性
![Snipaste_2022-07-27_10-03-05](https://user-images.githubusercontent.com/36778791/181145266-cbefb6d3-6fea-41ef-ba9c-6bd8ea03a0bb.png)
[2022-07-27T01_59_08_351Z-debug-0.log](https://github.com/yoimiya-kokomi/miao-plugin/files/9194461/2022-07-27T01_59_08_351Z-debug-0.log)

**Comment by sssysy** [comment]
![QQ截图20220728092826](https://user-images.githubusercontent.com/79786006/181400759-21e562e1-9d90-4493-85f2-3e9303748187.png)

**Comment by hsx-123** [comment]
> ![QQ截图20220728092826](https://user-images.githubusercontent.com/79786006/181400759-21e562e1-9d90-4493-85f2-3e9303748187.png)

同款报错

**Comment by ShiinaRinne** [comment]
> ![QQ截图20220728092826](https://user-images.githubusercontent.com/79786006/181400759-21e562e1-9d90-4493-85f2-3e9303748187.png)

试试yarn或者cnpm

**Comment by hsx-123** [comment]
cnpm可以，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月29日(周五) 晚上11:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yoimiya-kokomi/miao-plugin] 喵喵插件加载错误 (Issue #74)




  

  
试试yarn或者cnpm

**Comment by muguodiao** [comment]
![image](https://user-images.githubusercontent.com/105115300/181800311-6bd7fd62-a0bb-4923-ae66-672e81b67354.png)

**Comment by ShiinaRinne** [comment]
> ![image](https://user-images.githubusercontent.com/105115300/181800311-6bd7fd62-a0bb-4923-ae66-672e81b67354.png)

yarn需要额外安装，cnpm需要在cmd下执行，而不是powershell

**Comment by 4682265664** [comment]
shift 右键cmd
cnpm install image-size --save
搞定

**Comment by hsx-123** [comment]
已解决，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月1日(周一) 中午1:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yoimiya-kokomi/miao-plugin] 喵喵插件加载错误 (Issue #74)




 
shift 右键cmd
 cnpm install image-size --save
 搞定

**Comment by JiJiang233** [comment]
recv from: [Private: 3362710936(friend)] 喵喵帮助
[YzBot][02:25:06.450][MARK] puppeteer Chromium 启动中。。
[YzBot][02:25:06.471][ERRO] Error: Failed to launch the browser process!
/home/jijiang/Yunzai-Bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

[YzBot][02:25:06.471][ERRO] puppeteer Chromium 启动失败

这东西怎么安装

**Comment by cola2050** [comment]
> recv from: [Private: 3362710936(friend)] 喵喵帮助 [YzBot][02:25:06.450][MARK] puppeteer Chromium 启动中。。 [YzBot][02:25:06.471][ERRO] Error: Failed to launch the browser process! /home/jijiang/Yunzai-Bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> 
> [YzBot][02:25:06.471][ERRO] puppeteer Chromium 启动失败
> 
> 这东西怎么安装

**Comment by Donggzs** [comment]
深渊配队、体力推送和圣遗物评分（发截图）这三个到v3都没了。

**Comment by adjks45** [comment]
![image](https://user-images.githubusercontent.com/111344291/192140077-33520b8e-0ed2-4366-9d5d-936bdb7f5e01.png)
查看角色面板就出来网络错误什么原因？其他功能都还好

**Comment by ShiinaRinne** [comment]
> ![图片](https://user-images.githubusercontent.com/114035665/193057461-c750b960-3560-40d3-8464-87562ecfbbc1.png) 依赖按不上怎么解决

加个代理试试，或者用yarn、cnpm

**Comment by chen3a15** [comment]
![Screenshot_2022-10-14-09-53-07-03_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/110360823/195744035-1ccc0224-ea34-4acc-ad5b-35ae5daa4748.jpg)
各位大佬，这是怎么回事啊？

**Comment by caimogudelaomogu** [comment]
![QQ截图20221207130104](https://user-images.githubusercontent.com/119803214/206092768-4c66ebc8-5bef-4615-b725-0c0849cbe867.png)
![QQ图片20221207130029](https://user-images.githubusercontent.com/119803214/206092771-8421a778-a5f7-4a25-b974-ab7df8c5392a.png)
#56

**Comment by ziyuCat** [comment]
> recv from: [Private: 3362710936(friend)] 喵喵帮助 [YzBot][02:25:06.450][MARK] puppeteer Chromium 启动中。。 [YzBot][02:25:06.471][ERRO] Error: Failed to launch the browser process! /home/jijiang/Yunzai-Bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> 
> [YzBot][02:25:06.471][ERRO] puppeteer Chromium 启动失败
> 
> 这东西怎么安装

你解决了吗

**Comment by hanyangwendao** [comment]
> 
相同的问题，我使用了sudo yum install -y chromium。安装并解决了

**Comment by beilove** [comment]
这种错误该怎么办啊


|Miao-Yunzai  | [MiaoYz][18:39:22.811][ERRO] 载入插件错误：miao-plugin
|Miao-Yunzai  | [MiaoYz][18:39:22.812][ERRO] SyntaxError: Unexpected token '<<'
|Miao-Yunzai  |     at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
|Miao-Yunzai  |     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
|Miao-Yunzai  | [MiaoYz][18:39:23.014][INFO] - 正在载入 MJ-PLUGIN
|Miao-Yunzai  | Error: request "/gateway/bot" error with code(11244): token not exist or expire
|Miao-Yunzai  |     at C:\beichen\Miao-Yunzai\node_modules\.pnpm\qq-group-bot@1.0.30\node_modules\qq-group-bot\lib\qqBot.js:72:25
|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|Miao-Yunzai  |     at async Axios.request (C:\beichen\Miao-Yunzai\node_modules\.pnpm\axios@1.6.7_debug@2.6.9\node_modules\axios\dist\node\axios.cjs:3872:14)
|Miao-Yunzai  |     at Axios.request (C:\beichen\Miao-Yunzai\node_modules\.pnpm\axios@1.6.7_debug@2.6.9\node_modules\axios\dist\node\axios.cjs:3877:41)
|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|Miao-Yunzai  | [MiaoYz][18:39:23.238][ERRO] Error: request "/gateway/bot" error with code(11244): token not exist or expire
|Miao-Yunzai  |     at C:\beichen\Miao-Yunzai\node_modules\.pnpm\qq-group-bot@1.0.30\node_modules\qq-group-bot\lib\qqBot.js:72:25
|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|Miao-Yunzai  |     at async Axios.request (C:\beichen\Miao-Yunzai\node_modules\.pnpm\axios@1.6.7_debug@2.6.9\node_modules\axios\dist\node\axios.cjs:3872:14)
|Miao-Yunzai  |     at Axios.request (C:\beichen\Miao-Yunzai\node_modules\.pnpm\axios@1.6.7_debug@2.6.9\node_modules\axios\dist\node\axios.cjs:3877:41)
|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|Miao-Yunzai  | Error: request "/gateway/bot" error with code(11244): token not exist or expire
|Miao-Yunzai  |     at C:\beichen\Miao-Yunzai\node_modules\.pnpm\qq-group-bot@1.0.30\node_modules\qq-group-bot\lib\qqBot.js:72:25
|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|Miao-Yunzai  |     at async Axios.request (C:\beichen\Miao-Yunzai\node_modules\.pnpm\axios@1.6.7_debug@2.6.9\node_modules\axios\dist\node\axios.cjs:3872:14)
|Miao-Yunzai  |     at Axios.request (C:\beichen\Miao-Yunzai\node_modules\.pnpm\axios@1.6.7_debug@2.6.9\node_modules\axios\dist\node\axios.cjs:3877:41)
|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|Miao-Yunzai  | [MiaoYz][18:39:23.252][ERRO] Error: request "/gateway/bot" error with code(11244): token not exist or expire
|Miao-Yunzai  |     at C:\beichen\Miao-Yunzai\node_modules\.pnpm\qq-group-bot@1.0.30\node_modules\qq-group-bot\lib\qqBot.js:72:25
|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|Miao-Yunzai  |     at async Axios.request (C:\beichen\Miao-Yunzai\node_modules\.pnpm\axios@1.6.7_debug@2.6.9\node_modules\axios\dist\node\axios.cjs:3872:14)
|Miao-Yunzai  |     at Axios.request (C:\beichen\Miao-Yunzai\node_modules\.pnpm\axios@1.6.7_debug@2.6.9\node_modules\axios\dist\node\axios.cjs:3877:41)
|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by guXing1026** [comment]
大佬，求帮助，突然就这样了
重装了插件和依赖都没用

<img width="966" height="405" alt="Image" src="https://github.com/user-attachments/assets/ea12e79a-1c6c-4ed4-9ed0-486911180e38" />

**Comment by guXing1026** [comment]
> 大佬，求帮助，突然就这样了 重装了插件和依赖都没用
> 
> <img alt="Image" width="966" height="405" src="https://private-user-images.githubusercontent.com/116991666/493900508-ea12e79a-1c6c-4ed4-9ed0-486911180e38.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4MTcyNDAsIm5iZiI6MTc1ODgxNjk0MCwicGF0aCI6Ii8xMTY5OTE2NjYvNDkzOTAwNTA4LWVhMTJlNzlhLTFjNmMtNGVkNC05ZWQwLTQ4NjkxMTE4MGUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyNVQxNjE1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDYwMzNiN2Y5N2FhZGUxOWZlMWMxNDg0N2RlMWQ0NDhmOGNmNDhmYjY1YzAxNWRlNDhjYzllOTViZDNkNWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.73ZVHlTaUf6OfT84ikubK5LAgcIkrq3qXF0BpNCTBsM">

我把nodejs更新到v24.8.0 (Current)版本后就没出现了。。。。。。。。。。。
